export const GET_REQUEST = "GET_REQUEST";
export const GET_SUCCESS = "GET_SUCCESS";
export const GET_FAILURE = "GET_FAILURE";

export const GET__STATUS_REQUEST = "GET__STATUS_REQUEST";
export const GET__STATUS_SUCCESS = "GET__STATUS_SUCCESS";
export const GET__STATUS_FAILURE = "GET__STATUS_FAILURE";

export const ADD_REQUEST = "ADD_REQUEST";
export const ADD_SUCCESS = "ADD_SUCCESS";
export const ADD_FAILURE = "ADD_FAILURE";

export const ADD__STATUS_REQUEST = "ADD__STATUS_REQUEST";
export const ADD__STATUS_SUCCESS = "ADD__STATUS_SUCCESS";
export const ADD__STATUS_FAILURE = "ADD__STATUS_FAILURE";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";

export const DELETE__STATUS_REQUEST = "DELETE__STATUS_REQUEST";
export const DELETE__STATUS_SUCCESS = "DELETE__STATUS_SUCCESS";
export const DELETE__STATUS_FAILURE = "DELETE__STATUS_FAILURE";

export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAILURE = "UPDATE_FAILURE";

export const UPDATE__STATUS_REQUEST = "UPDATE__STATUS_REQUEST";
export const UPDATE__STATUS_SUCCESS = "UPDATE__STATUS_SUCCESS";
export const UPDATE__STATUS_FAILURE = "UPDATE__STATUS_FAILURE";
